
- name: 'create AutoStartupLogs directory'
  file:
    path: '{{apache_dir}}/apache/logs/AutoStartupLogs'
    state: directory
    owner: '{{ apache_system_user }}'
    group: '{{ apache_system_group }}'
    mode: "0755"
    recurse: yes

- name: Copy apache start script
  copy: 
    src: templates/apache.sh
    dest: "/usr/local/sbin/"
    group: root
    owner: root
    mode: '0755'
    force: yes

- name: Copy Apache service script
  copy:
    src: templates/apache.service
    dest: "/etc/systemd/system"
    group: root
    owner: root
    mode: '0755'
    force: yes

- name: enable Apache service
  command: "{{item}}"
  with_items:
    - systemctl enable apache.service
    - systemctl daemon-reload
    - ls -lrt /etc/systemd/system/default.target.wants/apache.service
  register: apache_enable

- name: Display output
  debug: var=apache_enable.results[2].stdout_lines

