---
- name: Change permission and ownership of WAS directories
  file: 
    state: directory
    path: "{{item}}"
    owner: "{{was_user}}"
    group: "{{was_grp}}"
    recurse: yes
  with_items:
    - "{{was_root}}"
    - "{{dir_was_path}}"
    #- "{{was_path}}"
 #   - "{{was_tmp}}"
    - "{{iim_path}}"
#    - "{{iim_repo}}"

- name: deleting binaries from source path
  file:
    path: "{{was_src}}/{{item}}"
    state: absent
  with_items:
    - "{{ was_files }}"

