- name: create ibm-was group
  group:
    name: '{{ apache_group }}'
    gid: '{{httpd_gid}}'
    system: true
    state: present

- name: create ibm-was user
  user:
    name: '{{ apache_user }}'
    group: '{{ apache_group }}'
    uid: '{{httpd_uid}}'
    createhome: true
    state: present
    system: true

