
- name: 'create AutoStartupLogs directory'
  file:
    path: '{{dir_app_http}}/logs/AutoStartupLogs'
    state: directory
    owner: '{{ apache_user }}'
    group: '{{ apache_group }}'
    mode: "0755"
    recurse: yes

- name: Copy ihs start script
  copy: 
    src: templates/ihs.sh
    dest: "/usr/local/sbin/"
    group: root
    owner: root
    mode: '0755'
    force: yes

- name: Copy ihs service script
  copy:
    src: templates/ihs.service
    dest: "/etc/systemd/system"
    group: root
    owner: root
    mode: '0755'
    force: yes

- name: enable IHS service
  command: "{{item}}"
  with_items:
    - systemctl enable ihs.service
    - systemctl daemon-reload
    - ls -lrt /etc/systemd/system/default.target.wants/ihs.service
  register: ihs_enable

- name: Display output
  debug: var=ihs_enable.results[2].stdout_lines
  

