---
#
# Variables
#######
apache_user: webadm
apache_group: webgrp
mount_point: /appl/IBM
#######
agent_installer: agent.installer.linux.gtk.x86_64_1.9.1004.20201109_1718.zip
dir_tmp_src: /appl/source
dir_ibm_im: /appl/source/ibm_im
dir_install_mgr: /appl/IBM/InstallationManager
