---
#
# Extract tomcat
#

- name: check if tomcat file exists.
  stat:
    path: '{{ tomcat_dir }}/tomcat/bin/catalina.sh'
  register: tomcat_extracted

# Ensure Tomcat Group and user accounts exists
- name: create tomcat group
  group:
    name: '{{ tomcat_system_group }}'
    system: true
    state: present

- name: create tomcat user
  user:
    name: '{{ tomcat_system_user }}'
    group: '{{ tomcat_system_group }}'
    createhome: true
    state: present
    system: true

- name: Install OpenJDK
  zypper:
    name: '{{ java_package }}'
    state: latest
  when: ansible_os_family == "Suse"

- name: Install OpenJDK
  yum:
    name: '{{ rhel_java_package }}'
    state: latest
  when: ansible_os_family == "RedHat"
 
 #when: tomcat_install_java

# Create an application directory if it does not exists
#- name: 'create application directory: {{ tomcat_dir }}'
#  file:
#    path: '{{ tomcat_dir }}'
#    owner: '{{ tomcat_system_user }}'
#    group: '{{ tomcat_system_group }}'
#    mode: '{{ tomcat_dir_mode }}'
#    recurse: true
#    state: directory
#  when: ( tomcat_extracted.stat.exists == false )


# Extract tomcat Archive
- name: Extract Tomcat Archive
  unarchive:
   src: "{{ tomcat_src }}/{{tomcat_package}}"
   dest: "{{tomcat_dir}}"
  # group: "{{tomcat_system_group}}"
  # owner: "{{tomcat_system_user}}"
  # mode: '0755'
   copy: no
   creates: '{{ tomcat_dir }}/tomcat/bin/catalina.sh'
  register: tomcat_package_extracted
  when: ( tomcat_extracted.stat.exists == false )

- name: Tomcat package extracted status
  debug:
    var: tomcat_package_extracted
