---
# tasks file for tomcat-ansible-role
- name: Preflight check
  include_tasks: preflight_check.yml

- name: Extract & Install Tomcat
  include_tasks: extract.yml

- name: Change Permissions
  include_tasks: chperm.yml

- name: creating Tomcat start and stop scripts when server reboots
  include_tasks: tomcat_restart.yml

- name: Tomcat log archive
  include_tasks: tomcat_log_archive.yml

- name: start tomcat 
  include_tasks: tomcat_run.yml

- name: Change Permissions
  include_tasks: chperm.yml

- name: Delete tomcat package in Source path
  include_tasks: remove_package.yml
