- name: Check {{ app_profile02 }} profile installation status on second node
  stat:
    path: "{{ profile_path }}/{{ app_profile02 }}"
  register: appsrv02

- name: Create {{ app_profile02 }} profile on second node
  become: true
  command:
    "{{ was_path }}/bin/manageprofiles.sh -create -profileName {{ app_profile02 }} -serverName {{ server_name02 }} -profilePath {{ was_path }}/profiles/{{ app_profile02 }} -templatePath {{ was_path }}/profileTemplates/default"
  when: appsrv02.stat.exists == False
