---
- name: copy pass
  become: true
  template:
    src: pass.sh.j2
    dest: "{{ pass_repo }}"
    mode: 0775

- name: Run Password Decrypt
  command: "{{ pass_repo }}"
  register: artifactid

- name: Setting Password fact
  set_fact:
    dcry_password: "{{ artifactid.stdout }}"

- name: Check first node federation status
  stat:
    path: "{{ profile_path }}/{{ app_profile01 }}/config/cells/plugin-cfg.xml"
  register: node01

- name: Federating first node with Dmgr
  become: true
  command: "{{ profile_path }}/{{ app_profile01 }}/bin/addNode.sh localhost 8879 -conntype soap -profileName {{ app_profile01 }} -username {{ was_adm_user }} -password {{ dcry_password }}"
  when: not node01.stat.exists
