---
- name:          KillAll Java
  command:       "killall -9 java"
  ignore_errors: true

# - name: Delete existing Websphere directories
#   file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - /etc/.ibm
#     - /opt/.ibm
#     - /opt/IBM
#     - /var/.ibm 
#     - /var/ibm

- name: "Executing Installation Manager"
  shell: "{{iim_repo}}/installc -acceptLicense -installationDirectory {{iim_path}} -log {{ was_tmp }}/im.log"
  register: cout
  changed_when:  (cout.stdout.find('Installed com.ibm.cic.agent') != -1)

- name: List Java Packages
  shell: "{{iim_path}}/eclipse/tools/imcl listAvailablepackages -repositories {{sdk_repo}}"
  register: java_package_list

- debug: var=java_package_list.stdout

- name: Filter Java Repo Name
  set_fact:
    java_repo_name: "{{ java_package_list.stdout | regex_search(regexp,'\\1') }}"
  vars:
    regexp: '(com.ibm.(websphere|java).(IBMJAVA|jdk).v[0-9]+_[0-9]+.[0-9]+.[0-9]+.[0-9]+_[0-9]*)'

- debug:
    msg: "{{java_repo_name}}"

- name: List IBM-WAS-ND Packages
  shell: "{{iim_path}}/eclipse/tools/imcl listAvailablepackages -repositories {{was_repo}}"
  register: ibm_was_nd_package_list

- name: Set Jave require as false
  set_fact:
    is_java_required: false

- name: Get IBM-WAS-ND Parent repo name
  set_fact:
    ibm_wasnd_repo_name: "{{ ibm_was_nd_package_list.stdout | regex_search(regexp,'\\1') }}"
  vars:
    regexp: '(com.ibm.[aA-zZ]+.ND.v(8|9)[0-9]_(8|9).[0-9].[0-9]+.[0-9]+_[0-9]+)'

- debug:
    msg: "{{ibm_wasnd_repo_name}}"

- name: Set flag to use java for IBM-WAS-ND 9.0.0
  set_fact:
    is_java_required: true
  when: ibm_was_nd_package_list.stdout | regex_search('(com.ibm.[aA-zZ]+.ND.v9[0-9]_9.[0-9].[0-9]+.[0-9]+_[0-9]+)','\\1')

- debug:
    msg: "Version of IBM-WAS-ND is 9.0.0"
  when: is_java_required

- name: Run IIM at {{ iim_path }} to install WAS at {{ was_path }}
  become: true
  command:
    "{{iim_path}}/eclipse/tools/imcl -acceptLicense install {{ java_repo_name[0]}} {{ ibm_wasnd_repo_name[0] }} -repositories {{ sdk_repo }},{{was_repo}} -installationDirectory {{ was_path }} -log {{ was_tmp }}/Was_install.log"
  register:      cout
  when: is_java_required
  changed_when:  (cout.stdout.find('Installed com.ibm.cic.agent') != -1)

- debug: var=cout
