- name: "Create Dmgr and {{ app_profile01 }} profiles on first node"
  include_tasks: create_profiles.yml

- name: "Start DMGR service"
  include_tasks: start_dmgr.yml

- name: "Federating first node with Dmgr"
  include_tasks: federate01.yml

- name: "Start  {{ app_profile01 }} service on first node"
  include_tasks: start_appsrvr01.yml

#- name: "Get first cluster node name"
#  include_tasks: get_cluster_node01.yml

#- name: "Add first cluster node"
#  include_tasks: add_cluster_node01.yml

