---
#
# Variables for IBM WebSphere Application Server
#
was_root: "/appl/source"
was_path: "/appl/IBM/WebSphere/AppServer/"
dir_was_path: "/appl/IBM/WebSphere"
was_src: "/appl/source"
was_tmp: "{{ was_root }}/tmp"
was_mode: "0755"
was_user: "wasadm"
was_grp: "wasgrp"
was_adm_user: "wasadmin"
dcrypt_password: "{{ hostvars[myhost[0]].dcry_password }}"
mount_point: /appl/IBM/
pass_repo: "/var/pass.sh"

iim_path: "/appl/IBM/InstallationManager"
iim_repo: "{{ was_root }}/ibm_im" #Used for extracting agent_installer.
iim_src_file: "agent.installer.linux.gtk.x86_64_1.9.1003.20200730_2125.zip"

sdk_repo: "{{ was_root}}/ibmsdk"
sdk_src_file: ibm-java-sdk-8.0-6.15-linux-x64-installmgr.zip

was_src_file: "WAS_ND_V9.0_MP_ML.zip"
was_src_file_fp: "9.0.5-WS-WAS-FP005.zip"
was_src_file_rp: "9.0.5-WS-WAS-RP.zip"
was_repo: "{{ was_root }}/WASND/"
was_repo_fp: "{{ was_root }}/WASND-FP/"      
was_repo_rp: "{{ was_root }}/WASND-RP/"
# was_repo1: "{{ was_repo }}/WASND_v8.5.5_Binaries/"
# was_imcl_package_name: "com.ibm.websphere.ND.v85_8.5.5000.20130514_1044"
dmgr_profile: "Dmgr01"
profile_path: "{{ was_path }}profiles"

server_name01: 'Server1'
server_name02: 'Server2'
app_profile01: 'AppSrv01'
app_profile02: 'AppSrv02'
wasadm_uid: 10010
wasadm_gid: 10010
cluster_name: 'cluster01'
#member_name01: '{{ ansible_hostname }}'
#member_name02: '{{ ansible_hostname }}'

required_vars:
  - was_root
  - was_path
  - was_src
  - was_tmp
  - was_mode
  - was_user
  - was_grp
  - iim_path
  - iim_repo
  - iim_src_file
  - was_src_file
  - was_repo
  - dmgr_profile
  - profile_path
  - server_name01
  - server_name02
  - app_profile01
  - app_profile02
  - cluster_name
#  - member_name01
#  - member_name02


was_files:
  - agent.installer.linux.gtk.x86_64_1.9.1003.20200730_2125.zip
  - 9.0.5-WS-WAS-RP.zip
  - 9.0.5-WS-WAS-FP005.zip
  - ibm-java-sdk-8.0-6.15-linux-x64-installmgr.zip
  - WAS_ND_V9.0_MP_ML.zip


