---
- name: Get server IP address
  set_fact:
    host_ip_add: '{{ansible_default_ipv4.address}}'

- name:  modify IP for management in config files
  shell: sed -i 's#<inet-address value="${jboss.bind.address.management:127.0.0.1}"/>#<inet-address value="${jboss.bind.address.management:{{host_ip_add}}}"/>#g' '{{jboss_app_dir }}/{{jboss_standalone_config_path}}/{{jboss_config_file}}'
  register: changed_mgmt

- debug:
    var: changed_mgmt

- name: modify IP for public address in config files
  shell: sed -i 's#<inet-address value="${jboss.bind.address:127.0.0.1}"/>#<inet-address value="${jboss.bind.address:{{host_ip_add}}}"/>#g' '{{jboss_app_dir }}/{{jboss_standalone_config_path}}/{{jboss_config_file}}'
  register: changed_public

- debug:
    var: changed_public

- name: modify IP for Private address in config files
  shell: sed -i 's#<inet-address value="${jboss.bind.address.private:127.0.0.1}"/>#<inet-address value="${jboss.bind.address.private:{{host_ip_add}}}"/>#g' '{{jboss_app_dir }}/{{jboss_standalone_config_path}}/{{jboss_config_file}}'
  register: changed_private
  when: jboss_config_file ==  "standalone-ha.xml" or jboss_config_file == "standalone-full-ha.xml"

- debug:
    var: changed_private

- name: modify IP for unsecure address in config files
  shell: sed -i 's#<inet-address value="${jboss.bind.address.unsecure:127.0.0.1}"/>#<inet-address value="${jboss.bind.address.unsecure:{{host_ip_add}}}"/>#g' '{{jboss_app_dir }}/{{jboss_standalone_config_path}}/{{jboss_config_file}}'
  register: changed_unsecure
  when: jboss_config_file == "standalone-full.xml" or jboss_config_file == "standalone-full-ha.xml"

- debug:
    var: changed_unsecure

