galaxy_info:
  author: Prudhvi
  description: Ansible role to install and configure Apache Tomcat on SUSE
  company: Hewlett Packard Enterprise
  license: MiT
  min_ansible_version: 2.3
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []
dependencies: []
