- name: find files '{{ dir_install_mgr }}'
  find:
    path: '{{ dir_install_mgr }}'
    file_type: file
  register: files

- name: find directories
  find:
    path: '{{ dir_install_mgr }}'
    file_type: directory
  register: directories

- name: Remove InstallarManager files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items:
    - '{{ files.files }}'
    - '{{ directories.files }}'

- name: find files in '{{dest_dir}}'
  find:
    path: '{{ dest_dir }}'
    file_type: file
  register: files

- name: find directories
  find:
    path: '{{ dest_dir }}'
    file_type: directory
  register: directories

- name: Remove InstallarManager files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items:
    - '{{ files.files }}'
    - '{{ directories.files }}'
