---
- name: "create tmp directory: "
  file:
    path: "{{appl_src}}/tmp"
    state: directory

- name: get Server node name
  shell: "grep 'Node name:' '{{ profile_path }}/{{ app_profile01 }}/logs/AboutThisProfile.txt' |cut -d: -f 2 | tr -d ' '"
  register: node_name

- name: Set timestamp
  set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: Set jython template as heap_size.jython
  set_fact:
    jython_template: heap_size.jython

- name: Copying jython script based on template {{ jython_template }}
  become: true
  template:
    src: "{{ jython_template }}"
    dest: "{{ appl_src }}/tmp/{{ jython_template }}.{{ timestamp }}.jy"
  changed_when: false
  when: jython_template is defined

- name: Running jython script {{ appl_src }}/tmp/{{ jython_template }}.{{ timestamp }}.jy
  become: true
  command:
    "{{ dest_dir }}/bin/wsadmin.sh -lang jython -user {{ was_user }} -password {{ dcrypt_password }} -f '{{ appl_src }}/tmp/{{ jython_template }}.{{ timestamp }}.jy'"
  when: jython_template is defined

- name: "Delete tmp directory: "
  file:
    path: "{{appl_src}}/tmp"
    state: absent
